// Swiss Postal Code Database - Core cities and regions
export const SWISS_POSTAL_CODES = [
  // Zurich
  { plz: '8001', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8002', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8003', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8004', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8005', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8006', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8007', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8008', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8009', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8010', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8037', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8038', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8042', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8044', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8045', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8046', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8047', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8048', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8049', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8050', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8051', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8052', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8053', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8055', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8056', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8057', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8058', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8059', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8060', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8064', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8070', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8090', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8091', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8092', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8093', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8094', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8095', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8096', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8097', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8098', ort: 'Zürich', kanton: 'ZH' },
  { plz: '8099', ort: 'Zürich', kanton: 'ZH' },
  
  // Bern
  { plz: '3011', ort: 'Bern', kanton: 'BE' },
  { plz: '3012', ort: 'Bern', kanton: 'BE' },
  { plz: '3013', ort: 'Bern', kanton: 'BE' },
  { plz: '3014', ort: 'Bern', kanton: 'BE' },
  { plz: '3015', ort: 'Bern', kanton: 'BE' },
  { plz: '3016', ort: 'Bern', kanton: 'BE' },
  { plz: '3017', ort: 'Bern', kanton: 'BE' },
  { plz: '3018', ort: 'Bern', kanton: 'BE' },
  { plz: '3019', ort: 'Bern', kanton: 'BE' },
  { plz: '3020', ort: 'Bern', kanton: 'BE' },
  
  // Basel-Stadt
  { plz: '4001', ort: 'Basel', kanton: 'BS' },
  { plz: '4002', ort: 'Basel', kanton: 'BS' },
  { plz: '4003', ort: 'Basel', kanton: 'BS' },
  { plz: '4004', ort: 'Basel', kanton: 'BS' },
  { plz: '4005', ort: 'Basel', kanton: 'BS' },
  { plz: '4006', ort: 'Basel', kanton: 'BS' },
  { plz: '4007', ort: 'Basel', kanton: 'BS' },
  { plz: '4008', ort: 'Basel', kanton: 'BS' },
  { plz: '4009', ort: 'Basel', kanton: 'BS' },
  { plz: '4010', ort: 'Basel', kanton: 'BS' },
  { plz: '4051', ort: 'Basel', kanton: 'BS' },
  { plz: '4052', ort: 'Basel', kanton: 'BS' },
  { plz: '4053', ort: 'Basel', kanton: 'BS' },
  { plz: '4054', ort: 'Basel', kanton: 'BS' },
  { plz: '4055', ort: 'Basel', kanton: 'BS' },
  { plz: '4056', ort: 'Basel', kanton: 'BS' },
  { plz: '4057', ort: 'Basel', kanton: 'BS' },
  { plz: '4058', ort: 'Basel', kanton: 'BS' },
  { plz: '4059', ort: 'Basel', kanton: 'BS' },
  { plz: '4125', ort: 'Riehen', kanton: 'BS' },
  { plz: '4126', ort: 'Bettingen', kanton: 'BS' },

  // Basel-Landschaft
  { plz: '4101', ort: 'Bruderholz', kanton: 'BL' },
  { plz: '4102', ort: 'Binningen', kanton: 'BL' },
  { plz: '4103', ort: 'Bottmingen', kanton: 'BL' },
  { plz: '4104', ort: 'Oberwil', kanton: 'BL' },
  { plz: '4105', ort: 'Biel-Benken', kanton: 'BL' },
  { plz: '4106', ort: 'Therwil', kanton: 'BL' },
  { plz: '4107', ort: 'Ettingen', kanton: 'BL' },
  { plz: '4108', ort: 'Witterswil', kanton: 'SO' },
  { plz: '4112', ort: 'Bättwil', kanton: 'SO' },
  { plz: '4114', ort: 'Hofstetten-Flüh', kanton: 'SO' },
  { plz: '4118', ort: 'Rodersdorf', kanton: 'SO' },
  { plz: '4123', ort: 'Allschwil', kanton: 'BL' },
  { plz: '4124', ort: 'Schönenbuch', kanton: 'BL' },
  { plz: '4127', ort: 'Birsfelden', kanton: 'BL' },
  { plz: '4132', ort: 'Muttenz', kanton: 'BL' },
  { plz: '4133', ort: 'Pratteln', kanton: 'BL' },
  { plz: '4142', ort: 'Münchenbuchsee', kanton: 'BL' },
  { plz: '4143', ort: 'Dornach', kanton: 'SO' },
  { plz: '4144', ort: 'Arlesheim', kanton: 'BL' },
  { plz: '4145', ort: 'Gempen', kanton: 'SO' },
  { plz: '4147', ort: 'Aesch', kanton: 'BL' },
  { plz: '4148', ort: 'Pfeffingen', kanton: 'BL' },
  { plz: '4153', ort: 'Reinach', kanton: 'BL' },
  { plz: '4154', ort: 'Reinach', kanton: 'BL' },
  { plz: '4410', ort: 'Liestal', kanton: 'BL' },
  { plz: '4411', ort: 'Seltisberg', kanton: 'BL' },
  { plz: '4412', ort: 'Nuglar', kanton: 'BL' },
  { plz: '4413', ort: 'Büren', kanton: 'BL' },
  { plz: '4414', ort: 'Füllinsdorf', kanton: 'BL' },
  { plz: '4415', ort: 'Lausen', kanton: 'BL' },
  { plz: '4416', ort: 'Bubendorf', kanton: 'BL' },
  { plz: '4417', ort: 'Ziefen', kanton: 'BL' },
  { plz: '4418', ort: 'Reigoldswil', kanton: 'BL' },
  { plz: '4419', ort: 'Lupsingen', kanton: 'BL' },
  { plz: '4422', ort: 'Arisdorf', kanton: 'BL' },
  { plz: '4423', ort: 'Hersberg', kanton: 'BL' },
  { plz: '4424', ort: 'Arboldswil', kanton: 'BL' },
  { plz: '4425', ort: 'Titterten', kanton: 'BL' },
  { plz: '4426', ort: 'Lauwil', kanton: 'BL' },
  { plz: '4431', ort: 'Bennwil', kanton: 'BL' },
  { plz: '4432', ort: 'Lampenberg', kanton: 'BL' },
  { plz: '4433', ort: 'Ramlinsburg', kanton: 'BL' },
  { plz: '4434', ort: 'Holstein', kanton: 'BL' },
  { plz: '4435', ort: 'Niederdorf', kanton: 'BL' },
  { plz: '4436', ort: 'Oberdorf', kanton: 'BL' },
  { plz: '4437', ort: 'Waldenburg', kanton: 'BL' },
  { plz: '4438', ort: 'Langenbruck', kanton: 'BL' },
  { plz: '4441', ort: 'Thürnen', kanton: 'BL' },
  { plz: '4442', ort: 'Diepflingen', kanton: 'BL' },
  { plz: '4443', ort: 'Wittinsburg', kanton: 'BL' },
  { plz: '4444', ort: 'Rümlingen', kanton: 'BL' },
  { plz: '4445', ort: 'Häfelfingen', kanton: 'BL' },
  { plz: '4446', ort: 'Buckten', kanton: 'BL' },
  { plz: '4447', ort: 'Känerkinden', kanton: 'BL' },
  { plz: '4448', ort: 'Läufelfingen', kanton: 'BL' },
  { plz: '4450', ort: 'Sissach', kanton: 'BL' },
  { plz: '4451', ort: 'Wintersingen', kanton: 'BL' },
  { plz: '4452', ort: 'Itingen', kanton: 'BL' },
  { plz: '4453', ort: 'Nusshof', kanton: 'BL' },
  { plz: '4455', ort: 'Zunzgen', kanton: 'BL' },
  { plz: '4456', ort: 'Tenniken', kanton: 'BL' },
  { plz: '4457', ort: 'Diegten', kanton: 'BL' },
  { plz: '4458', ort: 'Eptingen', kanton: 'BL' },
  { plz: '4460', ort: 'Gelterkinden', kanton: 'BL' },
  { plz: '4461', ort: 'Böckten', kanton: 'BL' },
  { plz: '4462', ort: 'Rickenbach', kanton: 'BL' },
  { plz: '4463', ort: 'Buus', kanton: 'BL' },
  { plz: '4464', ort: 'Maisprach', kanton: 'BL' },
  { plz: '4465', ort: 'Hemmiken', kanton: 'BL' },
  { plz: '4466', ort: 'Ormalingen', kanton: 'BL' },
  { plz: '4467', ort: 'Rothenfluh', kanton: 'BL' },
  { plz: '4468', ort: 'Kienberg', kanton: 'SO' },
  { plz: '4469', ort: 'Anwil', kanton: 'BL' },
  { plz: '4492', ort: 'Tecknau', kanton: 'BL' },
  { plz: '4493', ort: 'Wenslingen', kanton: 'BL' },
  { plz: '4494', ort: 'Oltingen', kanton: 'BL' },
  { plz: '4495', ort: 'Zeglingen', kanton: 'BL' },
  { plz: '4496', ort: 'Kilchberg', kanton: 'BL' },
  { plz: '4497', ort: 'Rünenberg', kanton: 'BL' },
  { plz: '4500', ort: 'Solothurn', kanton: 'SO' },
  { plz: '4501', ort: 'Solothurn', kanton: 'SO' },
  { plz: '4502', ort: 'Solothurn', kanton: 'SO' },
  { plz: '4503', ort: 'Solothurn', kanton: 'SO' },
  { plz: '4512', ort: 'Bellach', kanton: 'SO' },
  { plz: '4513', ort: 'Langendorf', kanton: 'SO' },
  { plz: '4514', ort: 'Lommiswil', kanton: 'SO' },
  { plz: '4515', ort: 'Oberdorf', kanton: 'SO' },
  { plz: '4600', ort: 'Olten', kanton: 'SO' },
  { plz: '4601', ort: 'Olten', kanton: 'SO' },
  { plz: '4603', ort: 'Olten', kanton: 'SO' },
  { plz: '4612', ort: 'Wangen', kanton: 'SO' },
  { plz: '4613', ort: 'Rickenbach', kanton: 'SO' },
  { plz: '4614', ort: 'Hägendorf', kanton: 'SO' },
  { plz: '4615', ort: 'Allerheiligenberg', kanton: 'SO' },
  { plz: '4616', ort: 'Kappel', kanton: 'SO' },
  { plz: '4617', ort: 'Gunzgen', kanton: 'SO' },
  { plz: '4618', ort: 'Boningen', kanton: 'SO' },
  { plz: '4622', ort: 'Egerkingen', kanton: 'SO' },
  { plz: '4623', ort: 'Neuendorf', kanton: 'SO' },
  { plz: '4624', ort: 'Härkingen', kanton: 'SO' },
  { plz: '4625', ort: 'Oberbuchsiten', kanton: 'SO' },
  { plz: '4626', ort: 'Niederbuchsiten', kanton: 'SO' },
  { plz: '4628', ort: 'Wolfwil', kanton: 'SO' },
  { plz: '4629', ort: 'Fulenbach', kanton: 'SO' },
  
  // Genève
  { plz: '1200', ort: 'Genève', kanton: 'GE' },
  { plz: '1201', ort: 'Genève', kanton: 'GE' },
  { plz: '1202', ort: 'Genève', kanton: 'GE' },
  { plz: '1203', ort: 'Genève', kanton: 'GE' },
  { plz: '1204', ort: 'Genève', kanton: 'GE' },
  { plz: '1205', ort: 'Genève', kanton: 'GE' },
  { plz: '1206', ort: 'Genève', kanton: 'GE' },
  { plz: '1207', ort: 'Genève', kanton: 'GE' },
  { plz: '1208', ort: 'Genève', kanton: 'GE' },
  { plz: '1209', ort: 'Genève', kanton: 'GE' },
  { plz: '1210', ort: 'Genève', kanton: 'GE' },
  { plz: '1211', ort: 'Genève', kanton: 'GE' },
  { plz: '1212', ort: 'Genève', kanton: 'GE' },
  { plz: '1213', ort: 'Genève', kanton: 'GE' },
  { plz: '1214', ort: 'Genève', kanton: 'GE' },
  { plz: '1215', ort: 'Genève', kanton: 'GE' },
  { plz: '1216', ort: 'Genève', kanton: 'GE' },
  { plz: '1217', ort: 'Genève', kanton: 'GE' },
  { plz: '1218', ort: 'Genève', kanton: 'GE' },
  { plz: '1219', ort: 'Genève', kanton: 'GE' },
  { plz: '1220', ort: 'Genève', kanton: 'GE' },
  { plz: '1221', ort: 'Genève', kanton: 'GE' },
  { plz: '1222', ort: 'Genève', kanton: 'GE' },
  { plz: '1223', ort: 'Genève', kanton: 'GE' },
  { plz: '1224', ort: 'Genève', kanton: 'GE' },
  { plz: '1225', ort: 'Genève', kanton: 'GE' },
  { plz: '1226', ort: 'Genève', kanton: 'GE' },
  { plz: '1227', ort: 'Genève', kanton: 'GE' },
  { plz: '1228', ort: 'Genève', kanton: 'GE' },
  { plz: '1229', ort: 'Genève', kanton: 'GE' },
  { plz: '1231', ort: 'Genève', kanton: 'GE' },
  { plz: '1232', ort: 'Genève', kanton: 'GE' },
  
  // Lausanne
  { plz: '1000', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1001', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1002', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1003', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1004', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1005', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1006', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1007', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1008', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1009', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1010', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1011', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1012', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1013', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1014', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1015', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1016', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1017', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1018', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1019', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1020', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1021', ort: 'Lausanne', kanton: 'VD' },
  { plz: '1022', ort: 'Lausanne', kanton: 'VD' },
  
  // Lucerne
  { plz: '6000', ort: 'Luzern', kanton: 'LU' },
  { plz: '6001', ort: 'Luzern', kanton: 'LU' },
  { plz: '6002', ort: 'Luzern', kanton: 'LU' },
  { plz: '6003', ort: 'Luzern', kanton: 'LU' },
  { plz: '6004', ort: 'Luzern', kanton: 'LU' },
  { plz: '6005', ort: 'Luzern', kanton: 'LU' },
  { plz: '6006', ort: 'Luzern', kanton: 'LU' },
  { plz: '6007', ort: 'Luzern', kanton: 'LU' },
  { plz: '6008', ort: 'Luzern', kanton: 'LU' },
  { plz: '6009', ort: 'Luzern', kanton: 'LU' },
  { plz: '6010', ort: 'Luzern', kanton: 'LU' },
  
  // St. Gallen
  { plz: '9000', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9001', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9002', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9003', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9004', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9005', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9006', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9007', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9008', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9009', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9010', ort: 'St. Gallen', kanton: 'SG' },
  { plz: '9011', ort: 'St. Gallen', kanton: 'SG' },
  
  // Winterthur
  { plz: '8400', ort: 'Winterthur', kanton: 'ZH' },
  { plz: '8401', ort: 'Winterthur', kanton: 'ZH' },
  { plz: '8402', ort: 'Winterthur', kanton: 'ZH' },
  { plz: '8403', ort: 'Winterthur', kanton: 'ZH' },
  { plz: '8404', ort: 'Winterthur', kanton: 'ZH' },
  { plz: '8405', ort: 'Winterthur', kanton: 'ZH' },
  
  // Aarau
  { plz: '5000', ort: 'Aarau', kanton: 'AG' },
  { plz: '5001', ort: 'Aarau', kanton: 'AG' },
  { plz: '5002', ort: 'Aarau', kanton: 'AG' },
  { plz: '5003', ort: 'Aarau', kanton: 'AG' },
];

/**
 * Lookup postal code and return city/canton
 */
export function lookupPostalCode(plz) {
  if (!plz || plz.length !== 4 || !/^\d+$/.test(plz)) {
    return null;
  }
  
  const matches = SWISS_POSTAL_CODES.filter(entry => entry.plz === plz);
  
  if (matches.length === 0) {
    return null;
  }
  
  if (matches.length === 1) {
    return matches[0];
  }
  
  // Multiple matches - return all
  return matches;
}

/**
 * Check if postal code is valid (4 digits)
 */
export function isValidPostalCode(plz) {
  return plz && plz.length === 4 && /^\d+$/.test(plz);
}