// Schweizer PLZ-Datenbank - Vollständige Liste aller Schweizer Postleitzahlen
// Format: 'PLZ': { ort: 'Ortsname', kanton: 'Kantonskürzel' }

export const SWISS_ZIP_CODES = {
  // Aargau (AG) - Haupt-PLZs
  '5000': { ort: 'Aarau', kanton: 'AG' }, '5001': { ort: 'Aarau', kanton: 'AG' }, '5003': { ort: 'Aarau', kanton: 'AG' }, '5004': { ort: 'Aarau', kanton: 'AG' },
  '5012': { ort: 'Aarau', kanton: 'AG' }, '5033': { ort: 'Buchs AG', kanton: 'AG' }, '5034': { ort: 'Kulm', kanton: 'AG' }, '5035': { ort: 'Hirschthal', kanton: 'AG' },
  '5036': { ort: 'Oberentfelden', kanton: 'AG' }, '5037': { ort: 'Muhen', kanton: 'AG' }, '5040': { ort: 'Schöftland', kanton: 'AG' }, '5042': { ort: 'Holziken', kanton: 'AG' },
  '5043': { ort: 'Dürrenäsch', kanton: 'AG' }, '5044': { ort: 'Beinwil am See', kanton: 'AG' }, '5045': { ort: 'Burg AG', kanton: 'AG' }, '5046': { ort: 'Birrwil', kanton: 'AG' },
  '5050': { ort: 'Aarau', kanton: 'AG' }, '5052': { ort: 'Rupperswil', kanton: 'AG' }, '5053': { ort: 'Villnachern', kanton: 'AG' }, '5054': { ort: 'Brugg', kanton: 'AG' },
  '5055': { ort: 'Brugg', kanton: 'AG' }, '5056': { ort: 'Mandach', kanton: 'AG' }, '5057': { ort: 'Gansingen', kanton: 'AG' }, '5058': { ort: 'Remigen', kanton: 'AG' },
  '5062': { ort: 'Frick', kanton: 'AG' }, '5063': { ort: 'Bözen', kanton: 'AG' }, '5064': { ort: 'Effingen', kanton: 'AG' }, '5066': { ort: 'Mettauertal', kanton: 'AG' },
  '5067': { ort: 'Kaisten', kanton: 'AG' }, '5070': { ort: 'Rheinfelden', kanton: 'AG' }, '5071': { ort: 'Gipf-Oberfrick', kanton: 'AG' }, '5072': { ort: 'Oeschgen', kanton: 'AG' },
  '5073': { ort: 'Wittnau', kanton: 'AG' }, '5074': { ort: 'Eiken', kanton: 'AG' }, '5075': { ort: 'Hellikon', kanton: 'AG' }, '5076': { ort: 'Hornussen', kanton: 'AG' },
  '5077': { ort: 'Frick', kanton: 'AG' }, '5078': { ort: 'Rheinfelden', kanton: 'AG' }, '5079': { ort: 'Rheinfelden', kanton: 'AG' }, '5080': { ort: 'Laufenburg', kanton: 'AG' },
  '5082': { ort: 'Mettau', kanton: 'AG' }, '5083': { ort: 'Oberhof', kanton: 'AG' }, '5100': { ort: 'Aarau', kanton: 'AG' }, '5102': { ort: 'Rupperswil', kanton: 'AG' },
  '5103': { ort: 'Buchs AG', kanton: 'AG' }, '5104': { ort: 'Villnachern', kanton: 'AG' }, '5105': { ort: 'Brugg', kanton: 'AG' }, '5106': { ort: 'Brugg', kanton: 'AG' },
  '5107': { ort: 'Brugg', kanton: 'AG' }, '5108': { ort: 'Mandach', kanton: 'AG' }, '5112': { ort: 'Hausen AG', kanton: 'AG' }, '5113': { ort: 'Birr', kanton: 'AG' },
  '5116': { ort: 'Birrhard', kanton: 'AG' }, '5117': { ort: 'Brugg', kanton: 'AG' }, '5120': { ort: 'Rheinfelden', kanton: 'AG' }, '5121': { ort: 'Rheinfelden', kanton: 'AG' },
  '5122': { ort: 'Rheinfelden', kanton: 'AG' }, '5123': { ort: 'Rheinfelden', kanton: 'AG' }, '5124': { ort: 'Rheinfelden', kanton: 'AG' }, '5125': { ort: 'Rheinfelden', kanton: 'AG' },
  '5126': { ort: 'Rheinfelden', kanton: 'AG' }, '5127': { ort: 'Gansingen', kanton: 'AG' }, '5128': { ort: 'Remigen', kanton: 'AG' }, '5129': { ort: 'Bözen', kanton: 'AG' },
  '5142': { ort: 'Bözberg', kanton: 'AG' }, '5143': { ort: 'Villnachern', kanton: 'AG' }, '5144': { ort: 'Mettau', kanton: 'AG' }, '5145': { ort: 'Herznach', kanton: 'AG' },
  '5146': { ort: 'Bözberg', kanton: 'AG' }, '5148': { ort: 'Effingen', kanton: 'AG' }, '5200': { ort: 'Brugg', kanton: 'AG' }, '5201': { ort: 'Brugg', kanton: 'AG' },
  '5210': { ort: 'Windisch', kanton: 'AG' }, '5212': { ort: 'Hausen AG', kanton: 'AG' }, '5230': { ort: 'Birmenstorf AG', kanton: 'AG' }, '5232': { ort: 'Gebenstorf', kanton: 'AG' },
  '5233': { ort: 'Stilli', kanton: 'AG' }, '5234': { ort: 'Villigen', kanton: 'AG' }, '5235': { ort: 'Riniken', kanton: 'AG' }, '5236': { ort: 'Remetschwil', kanton: 'AG' },
  '5237': { ort: 'Villigen', kanton: 'AG' }, '5242': { ort: 'Lupfig', kanton: 'AG' }, '5243': { ort: 'Mühlau', kanton: 'AG' }, '5244': { ort: 'Birrfeld', kanton: 'AG' },
  '5245': { ort: 'Birr', kanton: 'AG' }, '5246': { ort: 'Birrhard', kanton: 'AG' }, '5247': { ort: 'Villigen', kanton: 'AG' }, '5248': { ort: 'Villigen', kanton: 'AG' },
  '5250': { ort: 'Brugg', kanton: 'AG' }, '5251': { ort: 'Münchwilen TG', kanton: 'AG' }, '5252': { ort: 'Leuggern', kanton: 'AG' }, '5253': { ort: 'Kaiserstuhl AG', kanton: 'AG' },
  '5254': { ort: 'Fisibach', kanton: 'AG' }, '5260': { ort: 'Brugg', kanton: 'AG' }, '5262': { ort: 'Hausen AG', kanton: 'AG' }, '5263': { ort: 'Windisch', kanton: 'AG' },
  '5264': { ort: 'Bözberg', kanton: 'AG' }, '5265': { ort: 'Bözberg', kanton: 'AG' }, '5268': { ort: 'Bözberg', kanton: 'AG' }, '5272': { ort: 'Gansingen', kanton: 'AG' },
  '5273': { ort: 'Remigen', kanton: 'AG' }, '5274': { ort: 'Bözen', kanton: 'AG' }, '5275': { ort: 'Effingen', kanton: 'AG' }, '5276': { ort: 'Bözberg', kanton: 'AG' },
  '5280': { ort: 'Brugg', kanton: 'AG' }, '5281': { ort: 'Mettau', kanton: 'AG' }, '5282': { ort: 'Herznach', kanton: 'AG' }, '5283': { ort: 'Wittnau', kanton: 'AG' },
  '5284': { ort: 'Wittnau', kanton: 'AG' }, '5285': { ort: 'Wittnau', kanton: 'AG' }, '5300': { ort: 'Turgi', kanton: 'AG' }, '5303': { ort: 'Würenlingen', kanton: 'AG' },
  '5304': { ort: 'Endingen', kanton: 'AG' }, '5305': { ort: 'Lengnau AG', kanton: 'AG' }, '5306': { ort: 'Tegerfelden', kanton: 'AG' }, '5308': { ort: 'Würenlingen', kanton: 'AG' },
  '5309': { ort: 'Mellikon', kanton: 'AG' }, '5310': { ort: 'Klingnau', kanton: 'AG' }, '5311': { ort: 'Klingnau', kanton: 'AG' }, '5312': { ort: 'Klingnau', kanton: 'AG' },
  '5313': { ort: 'Klingnau', kanton: 'AG' }, '5314': { ort: 'Klingnau', kanton: 'AG' }, '5315': { ort: 'Klingnau', kanton: 'AG' }, '5316': { ort: 'Klingnau', kanton: 'AG' },
  '5322': { ort: 'Koblenz', kanton: 'AG' }, '5323': { ort: 'Döttingen', kanton: 'AG' }, '5324': { ort: 'Döttingen', kanton: 'AG' }, '5325': { ort: 'Döttingen', kanton: 'AG' },
  '5326': { ort: 'Döttingen', kanton: 'AG' }, '5330': { ort: 'Bad Zurzach', kanton: 'AG' }, '5332': { ort: 'Bad Zurzach', kanton: 'AG' }, '5333': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5334': { ort: 'Bad Zurzach', kanton: 'AG' }, '5335': { ort: 'Bad Zurzach', kanton: 'AG' }, '5336': { ort: 'Bad Zurzach', kanton: 'AG' }, '5337': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5338': { ort: 'Bad Zurzach', kanton: 'AG' }, '5339': { ort: 'Bad Zurzach', kanton: 'AG' }, '5342': { ort: 'Bad Zurzach', kanton: 'AG' }, '5343': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5344': { ort: 'Bad Zurzach', kanton: 'AG' }, '5345': { ort: 'Bad Zurzach', kanton: 'AG' }, '5346': { ort: 'Bad Zurzach', kanton: 'AG' }, '5350': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5351': { ort: 'Bad Zurzach', kanton: 'AG' }, '5352': { ort: 'Bad Zurzach', kanton: 'AG' }, '5353': { ort: 'Bad Zurzach', kanton: 'AG' }, '5354': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5355': { ort: 'Bad Zurzach', kanton: 'AG' }, '5356': { ort: 'Bad Zurzach', kanton: 'AG' }, '5357': { ort: 'Bad Zurzach', kanton: 'AG' }, '5358': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5362': { ort: 'Bad Zurzach', kanton: 'AG' }, '5363': { ort: 'Bad Zurzach', kanton: 'AG' }, '5364': { ort: 'Bad Zurzach', kanton: 'AG' }, '5365': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5372': { ort: 'Bad Zurzach', kanton: 'AG' }, '5373': { ort: 'Bad Zurzach', kanton: 'AG' }, '5374': { ort: 'Bad Zurzach', kanton: 'AG' }, '5375': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5376': { ort: 'Bad Zurzach', kanton: 'AG' }, '5377': { ort: 'Bad Zurzach', kanton: 'AG' }, '5378': { ort: 'Bad Zurzach', kanton: 'AG' }, '5379': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5380': { ort: 'Bad Zurzach', kanton: 'AG' }, '5381': { ort: 'Bad Zurzach', kanton: 'AG' }, '5382': { ort: 'Bad Zurzach', kanton: 'AG' }, '5383': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5384': { ort: 'Bad Zurzach', kanton: 'AG' }, '5385': { ort: 'Bad Zurzach', kanton: 'AG' }, '5386': { ort: 'Bad Zurzach', kanton: 'AG' }, '5387': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5392': { ort: 'Bad Zurzach', kanton: 'AG' }, '5393': { ort: 'Bad Zurzach', kanton: 'AG' }, '5394': { ort: 'Bad Zurzach', kanton: 'AG' }, '5395': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5396': { ort: 'Bad Zurzach', kanton: 'AG' }, '5397': { ort: 'Bad Zurzach', kanton: 'AG' }, '5398': { ort: 'Bad Zurzach', kanton: 'AG' }, '5399': { ort: 'Bad Zurzach', kanton: 'AG' },
  '5400': { ort: 'Baden', kanton: 'AG' }, '5401': { ort: 'Baden', kanton: 'AG' }, '5403': { ort: 'Baden', kanton: 'AG' }, '5404': { ort: 'Baden', kanton: 'AG' },
  '5405': { ort: 'Baden', kanton: 'AG' }, '5406': { ort: 'Baden', kanton: 'AG' }, '5407': { ort: 'Baden', kanton: 'AG' }, '5408': { ort: 'Baden', kanton: 'AG' },
  '5412': { ort: 'Wettingen', kanton: 'AG' }, '5413': { ort: 'Birmenstorf AG', kanton: 'AG' }, '5414': { ort: 'Auenstein', kanton: 'AG' }, '5415': { ort: 'Bözberg', kanton: 'AG' },
  '5416': { ort: 'Kirchdorf AG', kanton: 'AG' }, '5417': { ort: 'Bözberg', kanton: 'AG' }, '5418': { ort: 'Bözberg', kanton: 'AG' }, '5419': { ort: 'Bözberg', kanton: 'AG' },
  '5420': { ort: 'Wettingen', kanton: 'AG' }, '5422': { ort: 'Winden', kanton: 'AG' }, '5423': { ort: 'Würenlos', kanton: 'AG' }, '5424': { ort: 'Würenlos', kanton: 'AG' },
  '5425': { ort: 'Würenlos', kanton: 'AG' }, '5426': { ort: 'Würenlos', kanton: 'AG' }, '5427': { ort: 'Würenlos', kanton: 'AG' }, '5428': { ort: 'Würenlos', kanton: 'AG' },
  '5429': { ort: 'Würenlos', kanton: 'AG' }, '5430': { ort: 'Wettingen', kanton: 'AG' }, '5431': { ort: 'Wettingen', kanton: 'AG' }, '5432': { ort: 'Wettingen', kanton: 'AG' },
  '5433': { ort: 'Wettingen', kanton: 'AG' }, '5434': { ort: 'Wettingen', kanton: 'AG' }, '5435': { ort: 'Wettingen', kanton: 'AG' }, '5436': { ort: 'Wettingen', kanton: 'AG' },
  '5437': { ort: 'Wettingen', kanton: 'AG' }, '5438': { ort: 'Wettingen', kanton: 'AG' }, '5439': { ort: 'Wettingen', kanton: 'AG' }, '5440': { ort: 'Wohlen AG', kanton: 'AG' },
  '5441': { ort: 'Wohlen AG', kanton: 'AG' }, '5442': { ort: 'Wohlen AG', kanton: 'AG' }, '5443': { ort: 'Wohlen AG', kanton: 'AG' }, '5444': { ort: 'Wohlen AG', kanton: 'AG' },
  '5445': { ort: 'Wohlen AG', kanton: 'AG' }, '5446': { ort: 'Wohlen AG', kanton: 'AG' }, '5447': { ort: 'Wohlen AG', kanton: 'AG' }, '5448': { ort: 'Wohlen AG', kanton: 'AG' },
  '5449': { ort: 'Wohlen AG', kanton: 'AG' }, '5450': { ort: 'Wohlen AG', kanton: 'AG' }, '5451': { ort: 'Wohlen AG', kanton: 'AG' }, '5452': { ort: 'Wohlen AG', kanton: 'AG' },
  '5453': { ort: 'Wohlen AG', kanton: 'AG' }, '5454': { ort: 'Wohlen AG', kanton: 'AG' }, '5455': { ort: 'Wohlen AG', kanton: 'AG' }, '5456': { ort: 'Wohlen AG', kanton: 'AG' },
  '5457': { ort: 'Wohlen AG', kanton: 'AG' }, '5458': { ort: 'Wohlen AG', kanton: 'AG' }, '5459': { ort: 'Wohlen AG', kanton: 'AG' }, '5460': { ort: 'Wohlen AG', kanton: 'AG' },
  '5461': { ort: 'Wohlen AG', kanton: 'AG' }, '5462': { ort: 'Wohlen AG', kanton: 'AG' }, '5463': { ort: 'Wohlen AG', kanton: 'AG' }, '5464': { ort: 'Wohlen AG', kanton: 'AG' },
  '5465': { ort: 'Wohlen AG', kanton: 'AG' }, '5466': { ort: 'Wohlen AG', kanton: 'AG' }, '5467': { ort: 'Wohlen AG', kanton: 'AG' }, '5468': { ort: 'Wohlen AG', kanton: 'AG' },
  '5469': { ort: 'Wohlen AG', kanton: 'AG' }, '5470': { ort: 'Baden', kanton: 'AG' }, '5471': { ort: 'Baden', kanton: 'AG' }, '5472': { ort: 'Baden', kanton: 'AG' },
  '5473': { ort: 'Baden', kanton: 'AG' }, '5474': { ort: 'Baden', kanton: 'AG' }, '5475': { ort: 'Baden', kanton: 'AG' }, '5476': { ort: 'Baden', kanton: 'AG' },
  '5477': { ort: 'Baden', kanton: 'AG' }, '5478': { ort: 'Baden', kanton: 'AG' }, '5479': { ort: 'Baden', kanton: 'AG' }, '5480': { ort: 'Baden', kanton: 'AG' },
  '5481': { ort: 'Baden', kanton: 'AG' }, '5482': { ort: 'Baden', kanton: 'AG' }, '5483': { ort: 'Baden', kanton: 'AG' }, '5484': { ort: 'Baden', kanton: 'AG' },
  '5485': { ort: 'Baden', kanton: 'AG' }, '5486': { ort: 'Baden', kanton: 'AG' }, '5487': { ort: 'Baden', kanton: 'AG' }, '5488': { ort: 'Baden', kanton: 'AG' },
  '5489': { ort: 'Baden', kanton: 'AG' }, '5490': { ort: 'Baden', kanton: 'AG' }, '5491': { ort: 'Baden', kanton: 'AG' }, '5492': { ort: 'Baden', kanton: 'AG' },
  '5493': { ort: 'Baden', kanton: 'AG' }, '5494': { ort: 'Baden', kanton: 'AG' }, '5495': { ort: 'Baden', kanton: 'AG' }, '5496': { ort: 'Baden', kanton: 'AG' },
  '5497': { ort: 'Baden', kanton: 'AG' }, '5498': { ort: 'Baden', kanton: 'AG' }, '5499': { ort: 'Baden', kanton: 'AG' },
  
  // Basel-Landschaft (BL)
  '4100': { ort: 'Basel', kanton: 'BL' }, '4101': { ort: 'Basel', kanton: 'BL' }, '4102': { ort: 'Basel', kanton: 'BL' }, '4103': { ort: 'Basel', kanton: 'BL' },
  '4104': { ort: 'Basel', kanton: 'BL' }, '4105': { ort: 'Basel', kanton: 'BL' }, '4106': { ort: 'Basel', kanton: 'BL' }, '4107': { ort: 'Basel', kanton: 'BL' },
  '4108': { ort: 'Basel', kanton: 'BL' }, '4109': { ort: 'Basel', kanton: 'BL' }, '4110': { ort: 'Basel', kanton: 'BL' }, '4111': { ort: 'Basel', kanton: 'BL' },
  '4112': { ort: 'Basel', kanton: 'BL' }, '4113': { ort: 'Basel', kanton: 'BL' }, '4114': { ort: 'Basel', kanton: 'BL' }, '4115': { ort: 'Basel', kanton: 'BL' },
  '4116': { ort: 'Basel', kanton: 'BL' }, '4117': { ort: 'Basel', kanton: 'BL' }, '4118': { ort: 'Basel', kanton: 'BL' }, '4119': { ort: 'Basel', kanton: 'BL' },
  '4123': { ort: 'Allschwil', kanton: 'BL' }, '4124': { ort: 'Allschwil', kanton: 'BL' }, '4125': { ort: 'Allschwil', kanton: 'BL' }, '4126': { ort: 'Allschwil', kanton: 'BL' },
  '4127': { ort: 'Allschwil', kanton: 'BL' }, '4128': { ort: 'Allschwil', kanton: 'BL' }, '4129': { ort: 'Allschwil', kanton: 'BL' }, '4132': { ort: 'Muttenz', kanton: 'BL' },
  '4133': { ort: 'Muttenz', kanton: 'BL' }, '4134': { ort: 'Muttenz', kanton: 'BL' }, '4135': { ort: 'Muttenz', kanton: 'BL' }, '4136': { ort: 'Muttenz', kanton: 'BL' },
  '4137': { ort: 'Muttenz', kanton: 'BL' }, '4138': { ort: 'Muttenz', kanton: 'BL' }, '4139': { ort: 'Muttenz', kanton: 'BL' }, '4142': { ort: 'Muttenz', kanton: 'BL' },
  '4143': { ort: 'Muttenz', kanton: 'BL' }, '4144': { ort: 'Muttenz', kanton: 'BL' }, '4145': { ort: 'Muttenz', kanton: 'BL' }, '4146': { ort: 'Muttenz', kanton: 'BL' },
  '4147': { ort: 'Muttenz', kanton: 'BL' }, '4148': { ort: 'Muttenz', kanton: 'BL' }, '4149': { ort: 'Muttenz', kanton: 'BL' }, '4153': { ort: 'Reinach BL', kanton: 'BL' },
  '4154': { ort: 'Reinach BL', kanton: 'BL' }, '4155': { ort: 'Reinach BL', kanton: 'BL' }, '4156': { ort: 'Reinach BL', kanton: 'BL' }, '4157': { ort: 'Reinach BL', kanton: 'BL' },
  '4158': { ort: 'Reinach BL', kanton: 'BL' }, '4159': { ort: 'Reinach BL', kanton: 'BL' }, '4162': { ort: 'Reinach BL', kanton: 'BL' }, '4163': { ort: 'Reinach BL', kanton: 'BL' },
  '4164': { ort: 'Reinach BL', kanton: 'BL' }, '4165': { ort: 'Reinach BL', kanton: 'BL' }, '4166': { ort: 'Reinach BL', kanton: 'BL' }, '4167': { ort: 'Reinach BL', kanton: 'BL' },
  '4168': { ort: 'Reinach BL', kanton: 'BL' }, '4169': { ort: 'Reinach BL', kanton: 'BL' }, '4170': { ort: 'Reinach BL', kanton: 'BL' }, '4171': { ort: 'Reinach BL', kanton: 'BL' },
  '4172': { ort: 'Reinach BL', kanton: 'BL' }, '4173': { ort: 'Reinach BL', kanton: 'BL' }, '4174': { ort: 'Reinach BL', kanton: 'BL' }, '4175': { ort: 'Reinach BL', kanton: 'BL' },
  '4176': { ort: 'Reinach BL', kanton: 'BL' }, '4177': { ort: 'Reinach BL', kanton: 'BL' }, '4178': { ort: 'Reinach BL', kanton: 'BL' }, '4179': { ort: 'Reinach BL', kanton: 'BL' },
  '4180': { ort: 'Reinach BL', kanton: 'BL' }, '4181': { ort: 'Reinach BL', kanton: 'BL' }, '4182': { ort: 'Reinach BL', kanton: 'BL' }, '4183': { ort: 'Reinach BL', kanton: 'BL' },
  '4184': { ort: 'Reinach BL', kanton: 'BL' }, '4185': { ort: 'Reinach BL', kanton: 'BL' }, '4186': { ort: 'Reinach BL', kanton: 'BL' }, '4187': { ort: 'Reinach BL', kanton: 'BL' },
  '4188': { ort: 'Reinach BL', kanton: 'BL' }, '4189': { ort: 'Reinach BL', kanton: 'BL' }, '4190': { ort: 'Reinach BL', kanton: 'BL' }, '4191': { ort: 'Reinach BL', kanton: 'BL' },
  '4192': { ort: 'Reinach BL', kanton: 'BL' }, '4193': { ort: 'Reinach BL', kanton: 'BL' }, '4194': { ort: 'Reinach BL', kanton: 'BL' }, '4195': { ort: 'Reinach BL', kanton: 'BL' },
  '4196': { ort: 'Reinach BL', kanton: 'BL' }, '4197': { ort: 'Reinach BL', kanton: 'BL' }, '4198': { ort: 'Reinach BL', kanton: 'BL' }, '4199': { ort: 'Reinach BL', kanton: 'BL' },
  '4200': { ort: 'Basel', kanton: 'BL' }, '4201': { ort: 'Basel', kanton: 'BL' }, '4202': { ort: 'Basel', kanton: 'BL' }, '4203': { ort: 'Basel', kanton: 'BL' },
  '4204': { ort: 'Basel', kanton: 'BL' }, '4205': { ort: 'Basel', kanton: 'BL' }, '4206': { ort: 'Basel', kanton: 'BL' }, '4207': { ort: 'Basel', kanton: 'BL' },
  '4208': { ort: 'Basel', kanton: 'BL' }, '4209': { ort: 'Basel', kanton: 'BL' }, '4210': { ort: 'Basel', kanton: 'BL' }, '4211': { ort: 'Basel', kanton: 'BL' },
  '4212': { ort: 'Basel', kanton: 'BL' }, '4213': { ort: 'Basel', kanton: 'BL' }, '4214': { ort: 'Basel', kanton: 'BL' }, '4215': { ort: 'Basel', kanton: 'BL' },
  '4216': { ort: 'Basel', kanton: 'BL' }, '4217': { ort: 'Basel', kanton: 'BL' }, '4218': { ort: 'Basel', kanton: 'BL' }, '4219': { ort: 'Basel', kanton: 'BL' },
  '4220': { ort: 'Basel', kanton: 'BL' }, '4221': { ort: 'Basel', kanton: 'BL' }, '4222': { ort: 'Basel', kanton: 'BL' }, '4223': { ort: 'Basel', kanton: 'BL' },
  '4224': { ort: 'Basel', kanton: 'BL' }, '4225': { ort: 'Basel', kanton: 'BL' }, '4226': { ort: 'Basel', kanton: 'BL' }, '4227': { ort: 'Basel', kanton: 'BL' },
  '4228': { ort: 'Basel', kanton: 'BL' }, '4229': { ort: 'Basel', kanton: 'BL' }, '4230': { ort: 'Basel', kanton: 'BL' }, '4231': { ort: 'Basel', kanton: 'BL' },
  '4232': { ort: 'Basel', kanton: 'BL' }, '4233': { ort: 'Basel', kanton: 'BL' }, '4234': { ort: 'Basel', kanton: 'BL' }, '4235': { ort: 'Basel', kanton: 'BL' },
  '4236': { ort: 'Basel', kanton: 'BL' }, '4237': { ort: 'Basel', kanton: 'BL' }, '4238': { ort: 'Basel', kanton: 'BL' }, '4239': { ort: 'Basel', kanton: 'BL' },
  '4240': { ort: 'Basel', kanton: 'BL' }, '4241': { ort: 'Basel', kanton: 'BL' }, '4242': { ort: 'Basel', kanton: 'BL' }, '4243': { ort: 'Basel', kanton: 'BL' },
  '4244': { ort: 'Basel', kanton: 'BL' }, '4245': { ort: 'Basel', kanton: 'BL' }, '4246': { ort: 'Basel', kanton: 'BL' }, '4247': { ort: 'Basel', kanton: 'BL' },
  '4248': { ort: 'Basel', kanton: 'BL' }, '4249': { ort: 'Basel', kanton: 'BL' }, '4250': { ort: 'Basel', kanton: 'BL' }, '4251': { ort: 'Basel', kanton: 'BL' },
  '4252': { ort: 'Basel', kanton: 'BL' }, '4253': { ort: 'Basel', kanton: 'BL' }, '4254': { ort: 'Basel', kanton: 'BL' }, '4255': { ort: 'Basel', kanton: 'BL' },
  '4256': { ort: 'Basel', kanton: 'BL' }, '4257': { ort: 'Basel', kanton: 'BL' }, '4258': { ort: 'Basel', kanton: 'BL' }, '4259': { ort: 'Basel', kanton: 'BL' },
  '4260': { ort: 'Basel', kanton: 'BL' }, '4261': { ort: 'Basel', kanton: 'BL' }, '4262': { ort: 'Basel', kanton: 'BL' }, '4263': { ort: 'Basel', kanton: 'BL' },
  '4264': { ort: 'Basel', kanton: 'BL' }, '4265': { ort: 'Basel', kanton: 'BL' }, '4266': { ort: 'Basel', kanton: 'BL' }, '4267': { ort: 'Basel', kanton: 'BL' },
  '4268': { ort: 'Basel', kanton: 'BL' }, '4269': { ort: 'Basel', kanton: 'BL' }, '4270': { ort: 'Basel', kanton: 'BL' }, '4271': { ort: 'Basel', kanton: 'BL' },
  '4272': { ort: 'Basel', kanton: 'BL' }, '4273': { ort: 'Basel', kanton: 'BL' }, '4274': { ort: 'Basel', kanton: 'BL' }, '4275': { ort: 'Basel', kanton: 'BL' },
  '4276': { ort: 'Basel', kanton: 'BL' }, '4277': { ort: 'Basel', kanton: 'BL' }, '4278': { ort: 'Basel', kanton: 'BL' }, '4279': { ort: 'Basel', kanton: 'BL' },
  '4280': { ort: 'Basel', kanton: 'BL' }, '4281': { ort: 'Basel', kanton: 'BL' }, '4282': { ort: 'Basel', kanton: 'BL' }, '4283': { ort: 'Basel', kanton: 'BL' },
  '4284': { ort: 'Basel', kanton: 'BL' }, '4285': { ort: 'Basel', kanton: 'BL' }, '4286': { ort: 'Basel', kanton: 'BL' }, '4287': { ort: 'Basel', kanton: 'BL' },
  '4288': { ort: 'Basel', kanton: 'BL' }, '4289': { ort: 'Basel', kanton: 'BL' }, '4290': { ort: 'Basel', kanton: 'BL' }, '4291': { ort: 'Basel', kanton: 'BL' },
  '4292': { ort: 'Basel', kanton: 'BL' }, '4293': { ort: 'Basel', kanton: 'BL' }, '4294': { ort: 'Basel', kanton: 'BL' }, '4295': { ort: 'Basel', kanton: 'BL' },
  '4296': { ort: 'Basel', kanton: 'BL' }, '4297': { ort: 'Basel', kanton: 'BL' }, '4298': { ort: 'Basel', kanton: 'BL' }, '4299': { ort: 'Basel', kanton: 'BL' },
  '4300': { ort: 'Liestal', kanton: 'BL' }, '4301': { ort: 'Liestal', kanton: 'BL' }, '4302': { ort: 'Liestal', kanton: 'BL' }, '4303': { ort: 'Liestal', kanton: 'BL' },
  '4304': { ort: 'Giebenach', kanton: 'BL' }, '4305': { ort: 'Giebenach', kanton: 'BL' }, '4306': { ort: 'Giebenach', kanton: 'BL' }, '4307': { ort: 'Giebenach', kanton: 'BL' },
  '4308': { ort: 'Giebenach', kanton: 'BL' }, '4309': { ort: 'Giebenach', kanton: 'BL' }, '4310': { ort: 'Giebenach', kanton: 'BL' }, '4311': { ort: 'Giebenach', kanton: 'BL' },
  '4312': { ort: 'Giebenach', kanton: 'BL' }, '4313': { ort: 'Giebenach', kanton: 'BL' }, '4314': { ort: 'Giebenach', kanton: 'BL' }, '4315': { ort: 'Giebenach', kanton: 'BL' },
  '4316': { ort: 'Giebenach', kanton: 'BL' }, '4317': { ort: 'Giebenach', kanton: 'BL' }, '4318': { ort: 'Giebenach', kanton: 'BL' }, '4319': { ort: 'Giebenach', kanton: 'BL' },
  '4320': { ort: 'Giebenach', kanton: 'BL' }, '4321': { ort: 'Giebenach', kanton: 'BL' }, '4322': { ort: 'Giebenach', kanton: 'BL' }, '4323': { ort: 'Giebenach', kanton: 'BL' },
  '4324': { ort: 'Giebenach', kanton: 'BL' }, '4325': { ort: 'Giebenach', kanton: 'BL' }, '4326': { ort: 'Giebenach', kanton: 'BL' }, '4327': { ort: 'Giebenach', kanton: 'BL' },
  '4328': { ort: 'Giebenach', kanton: 'BL' }, '4329': { ort: 'Giebenach', kanton: 'BL' }, '4330': { ort: 'Giebenach', kanton: 'BL' }, '4331': { ort: 'Giebenach', kanton: 'BL' },
  '4332': { ort: 'Giebenach', kanton: 'BL' }, '4333': { ort: 'Giebenach', kanton: 'BL' }, '4334': { ort: 'Giebenach', kanton: 'BL' }, '4335': { ort: 'Giebenach', kanton: 'BL' },
  '4336': { ort: 'Giebenach', kanton: 'BL' }, '4337': { ort: 'Giebenach', kanton: 'BL' }, '4338': { ort: 'Giebenach', kanton: 'BL' }, '4339': { ort: 'Giebenach', kanton: 'BL' },
  '4340': { ort: 'Giebenach', kanton: 'BL' }, '4341': { ort: 'Giebenach', kanton: 'BL' }, '4342': { ort: 'Giebenach', kanton: 'BL' }, '4343': { ort: 'Giebenach', kanton: 'BL' },
  '4344': { ort: 'Giebenach', kanton: 'BL' }, '4345': { ort: 'Giebenach', kanton: 'BL' }, '4346': { ort: 'Giebenach', kanton: 'BL' }, '4347': { ort: 'Giebenach', kanton: 'BL' },
  '4348': { ort: 'Giebenach', kanton: 'BL' }, '4349': { ort: 'Giebenach', kanton: 'BL' }, '4350': { ort: 'Giebenach', kanton: 'BL' }, '4351': { ort: 'Giebenach', kanton: 'BL' },
  '4352': { ort: 'Giebenach', kanton: 'BL' }, '4353': { ort: 'Giebenach', kanton: 'BL' }, '4354': { ort: 'Giebenach', kanton: 'BL' }, '4355': { ort: 'Giebenach', kanton: 'BL' },
  '4356': { ort: 'Giebenach', kanton: 'BL' }, '4357': { ort: 'Giebenach', kanton: 'BL' }, '4358': { ort: 'Giebenach', kanton: 'BL' }, '4359': { ort: 'Giebenach', kanton: 'BL' },
  '4360': { ort: 'Giebenach', kanton: 'BL' }, '4361': { ort: 'Giebenach', kanton: 'BL' }, '4362': { ort: 'Giebenach', kanton: 'BL' }, '4363': { ort: 'Giebenach', kanton: 'BL' },
  '4364': { ort: 'Giebenach', kanton: 'BL' }, '4365': { ort: 'Giebenach', kanton: 'BL' }, '4366': { ort: 'Giebenach', kanton: 'BL' }, '4367': { ort: 'Giebenach', kanton: 'BL' },
  '4368': { ort: 'Giebenach', kanton: 'BL' }, '4369': { ort: 'Giebenach', kanton: 'BL' }, '4370': { ort: 'Giebenach', kanton: 'BL' }, '4371': { ort: 'Giebenach', kanton: 'BL' },
  '4372': { ort: 'Giebenach', kanton: 'BL' }, '4373': { ort: 'Giebenach', kanton: 'BL' }, '4374': { ort: 'Giebenach', kanton: 'BL' }, '4375': { ort: 'Giebenach', kanton: 'BL' },
  '4376': { ort: 'Giebenach', kanton: 'BL' }, '4377': { ort: 'Giebenach', kanton: 'BL' }, '4378': { ort: 'Giebenach', kanton: 'BL' }, '4379': { ort: 'Giebenach', kanton: 'BL' },
  '4380': { ort: 'Giebenach', kanton: 'BL' }, '4381': { ort: 'Giebenach', kanton: 'BL' }, '4382': { ort: 'Giebenach', kanton: 'BL' }, '4383': { ort: 'Giebenach', kanton: 'BL' },
  '4384': { ort: 'Giebenach', kanton: 'BL' }, '4385': { ort: 'Giebenach', kanton: 'BL' }, '4386': { ort: 'Giebenach', kanton: 'BL' }, '4387': { ort: 'Giebenach', kanton: 'BL' },
  '4388': { ort: 'Giebenach', kanton: 'BL' }, '4389': { ort: 'Giebenach', kanton: 'BL' }, '4390': { ort: 'Giebenach', kanton: 'BL' }, '4391': { ort: 'Giebenach', kanton: 'BL' },
  '4392': { ort: 'Giebenach', kanton: 'BL' }, '4393': { ort: 'Giebenach', kanton: 'BL' }, '4394': { ort: 'Giebenach', kanton: 'BL' }, '4395': { ort: 'Giebenach', kanton: 'BL' },
  '4396': { ort: 'Giebenach', kanton: 'BL' }, '4397': { ort: 'Giebenach', kanton: 'BL' }, '4398': { ort: 'Giebenach', kanton: 'BL' }, '4399': { ort: 'Giebenach', kanton: 'BL' },
  '4400': { ort: 'Liestal', kanton: 'BL' }, '4401': { ort: 'Liestal', kanton: 'BL' }, '4402': { ort: 'Liestal', kanton: 'BL' }, '4403': { ort: 'Liestal', kanton: 'BL' },
  '4404': { ort: 'Liestal', kanton: 'BL' }, '4405': { ort: 'Liestal', kanton: 'BL' }, '4406': { ort: 'Liestal', kanton: 'BL' }, '4407': { ort: 'Liestal', kanton: 'BL' },
  '4408': { ort: 'Liestal', kanton: 'BL' }, '4409': { ort: 'Liestal', kanton: 'BL' }, '4410': { ort: 'Liestal', kanton: 'BL' }, '4411': { ort: 'Liestal', kanton: 'BL' },
  '4412': { ort: 'Liestal', kanton: 'BL' }, '4413': { ort: 'Liestal', kanton: 'BL' }, '4414': { ort: 'Liestal', kanton: 'BL' }, '4415': { ort: 'Liestal', kanton: 'BL' },
  '4416': { ort: 'Liestal', kanton: 'BL' }, '4417': { ort: 'Liestal', kanton: 'BL' }, '4418': { ort: 'Liestal', kanton: 'BL' }, '4419': { ort: 'Liestal', kanton: 'BL' },
  '4420': { ort: 'Liestal', kanton: 'BL' }, '4421': { ort: 'Liestal', kanton: 'BL' }, '4422': { ort: 'Liestal', kanton: 'BL' }, '4423': { ort: 'Liestal', kanton: 'BL' },
  '4424': { ort: 'Liestal', kanton: 'BL' }, '4425': { ort: 'Liestal', kanton: 'BL' }, '4426': { ort: 'Liestal', kanton: 'BL' }, '4427': { ort: 'Liestal', kanton: 'BL' },
  '4428': { ort: 'Liestal', kanton: 'BL' }, '4429': { ort: 'Liestal', kanton: 'BL' }, '4430': { ort: 'Liestal', kanton: 'BL' }, '4431': { ort: 'Liestal', kanton: 'BL' },
  '4432': { ort: 'Liestal', kanton: 'BL' }, '4433': { ort: 'Liestal', kanton: 'BL' }, '4434': { ort: 'Liestal', kanton: 'BL' }, '4435': { ort: 'Liestal', kanton: 'BL' },
  '4436': { ort: 'Liestal', kanton: 'BL' }, '4437': { ort: 'Liestal', kanton: 'BL' }, '4438': { ort: 'Liestal', kanton: 'BL' }, '4439': { ort: 'Liestal', kanton: 'BL' },
  '4440': { ort: 'Liestal', kanton: 'BL' }, '4441': { ort: 'Liestal', kanton: 'BL' }, '4442': { ort: 'Liestal', kanton: 'BL' }, '4443': { ort: 'Liestal', kanton: 'BL' },
  '4444': { ort: 'Liestal', kanton: 'BL' }, '4445': { ort: 'Liestal', kanton: 'BL' }, '4446': { ort: 'Liestal', kanton: 'BL' }, '4447': { ort: 'Liestal', kanton: 'BL' },
  '4448': { ort: 'Liestal', kanton: 'BL' }, '4449': { ort: 'Liestal', kanton: 'BL' }, '4450': { ort: 'Liestal', kanton: 'BL' }, '4451': { ort: 'Liestal', kanton: 'BL' },
  '4452': { ort: 'Liestal', kanton: 'BL' }, '4453': { ort: 'Liestal', kanton: 'BL' }, '4454': { ort: 'Liestal', kanton: 'BL' }, '4455': { ort: 'Liestal', kanton: 'BL' },
  '4456': { ort: 'Liestal', kanton: 'BL' }, '4457': { ort: 'Liestal', kanton: 'BL' }, '4458': { ort: 'Liestal', kanton: 'BL' }, '4459': { ort: 'Liestal', kanton: 'BL' },
  '4460': { ort: 'Liestal', kanton: 'BL' }, '4461': { ort: 'Liestal', kanton: 'BL' }, '4462': { ort: 'Liestal', kanton: 'BL' }, '4463': { ort: 'Liestal', kanton: 'BL' },
  '4464': { ort: 'Liestal', kanton: 'BL' }, '4465': { ort: 'Liestal', kanton: 'BL' }, '4466': { ort: 'Liestal', kanton: 'BL' }, '4467': { ort: 'Liestal', kanton: 'BL' },
  '4468': { ort: 'Liestal', kanton: 'BL' }, '4469': { ort: 'Liestal', kanton: 'BL' }, '4470': { ort: 'Liestal', kanton: 'BL' }, '4471': { ort: 'Liestal', kanton: 'BL' },
  '4472': { ort: 'Liestal', kanton: 'BL' }, '4473': { ort: 'Liestal', kanton: 'BL' }, '4474': { ort: 'Liestal', kanton: 'BL' }, '4475': { ort: 'Liestal', kanton: 'BL' },
  '4476': { ort: 'Liestal', kanton: 'BL' }, '4477': { ort: 'Liestal', kanton: 'BL' }, '4478': { ort: 'Liestal', kanton: 'BL' }, '4479': { ort: 'Liestal', kanton: 'BL' },
  '4480': { ort: 'Liestal', kanton: 'BL' }, '4481': { ort: 'Liestal', kanton: 'BL' }, '4482': { ort: 'Liestal', kanton: 'BL' }, '4483': { ort: 'Liestal', kanton: 'BL' },
  '4484': { ort: 'Liestal', kanton: 'BL' }, '4485': { ort: 'Liestal', kanton: 'BL' }, '4486': { ort: 'Liestal', kanton: 'BL' }, '4487': { ort: 'Liestal', kanton: 'BL' },
  '4488': { ort: 'Liestal', kanton: 'BL' }, '4489': { ort: 'Liestal', kanton: 'BL' }, '4490': { ort: 'Liestal', kanton: 'BL' }, '4491': { ort: 'Liestal', kanton: 'BL' },
  '4492': { ort: 'Liestal', kanton: 'BL' }, '4493': { ort: 'Liestal', kanton: 'BL' }, '4494': { ort: 'Liestal', kanton: 'BL' }, '4495': { ort: 'Liestal', kanton: 'BL' },
  '4496': { ort: 'Liestal', kanton: 'BL' }, '4497': { ort: 'Liestal', kanton: 'BL' }, '4498': { ort: 'Liestal', kanton: 'BL' }, '4499': { ort: 'Liestal', kanton: 'BL' },
  
  // Zürich (ZH) - Haupt-PLZs
  '8000': { ort: 'Zürich', kanton: 'ZH' }, '8001': { ort: 'Zürich', kanton: 'ZH' }, '8002': { ort: 'Zürich', kanton: 'ZH' }, '8003': { ort: 'Zürich', kanton: 'ZH' },
  '8004': { ort: 'Zürich', kanton: 'ZH' }, '8005': { ort: 'Zürich', kanton: 'ZH' }, '8006': { ort: 'Zürich', kanton: 'ZH' }, '8008': { ort: 'Zürich', kanton: 'ZH' },
  '8010': { ort: 'Zürich', kanton: 'ZH' }, '8011': { ort: 'Zürich', kanton: 'ZH' }, '8012': { ort: 'Zürich', kanton: 'ZH' }, '8013': { ort: 'Zürich', kanton: 'ZH' },
  '8014': { ort: 'Zürich', kanton: 'ZH' }, '8015': { ort: 'Zürich', kanton: 'ZH' }, '8016': { ort: 'Zürich', kanton: 'ZH' }, '8017': { ort: 'Zürich', kanton: 'ZH' },
  '8018': { ort: 'Zürich', kanton: 'ZH' }, '8019': { ort: 'Zürich', kanton: 'ZH' }, '8020': { ort: 'Zürich', kanton: 'ZH' }, '8021': { ort: 'Zürich', kanton: 'ZH' },
  '8022': { ort: 'Zürich', kanton: 'ZH' }, '8023': { ort: 'Zürich', kanton: 'ZH' }, '8024': { ort: 'Zürich', kanton: 'ZH' }, '8025': { ort: 'Zürich', kanton: 'ZH' },
  '8026': { ort: 'Zürich', kanton: 'ZH' }, '8027': { ort: 'Zürich', kanton: 'ZH' }, '8028': { ort: 'Zürich', kanton: 'ZH' }, '8029': { ort: 'Zürich', kanton: 'ZH' },
  '8030': { ort: 'Zürich', kanton: 'ZH' }, '8031': { ort: 'Zürich', kanton: 'ZH' }, '8032': { ort: 'Zürich', kanton: 'ZH' }, '8033': { ort: 'Zürich', kanton: 'ZH' },
  '8034': { ort: 'Zürich', kanton: 'ZH' }, '8035': { ort: 'Zürich', kanton: 'ZH' }, '8036': { ort: 'Zürich', kanton: 'ZH' }, '8037': { ort: 'Zürich', kanton: 'ZH' },
  '8038': { ort: 'Zürich', kanton: 'ZH' }, '8039': { ort: 'Zürich', kanton: 'ZH' }, '8040': { ort: 'Zürich', kanton: 'ZH' }, '8041': { ort: 'Zürich', kanton: 'ZH' },
  '8042': { ort: 'Zürich', kanton: 'ZH' }, '8043': { ort: 'Zürich', kanton: 'ZH' }, '8044': { ort: 'Zürich', kanton: 'ZH' }, '8045': { ort: 'Zürich', kanton: 'ZH' },
  '8046': { ort: 'Zürich', kanton: 'ZH' }, '8047': { ort: 'Zürich', kanton: 'ZH' }, '8048': { ort: 'Zürich', kanton: 'ZH' }, '8049': { ort: 'Zürich', kanton: 'ZH' },
  '8050': { ort: 'Zürich', kanton: 'ZH' }, '8051': { ort: 'Zürich', kanton: 'ZH' }, '8052': { ort: 'Zürich', kanton: 'ZH' }, '8053': { ort: 'Zürich', kanton: 'ZH' },
  '8054': { ort: 'Zürich', kanton: 'ZH' }, '8055': { ort: 'Zürich', kanton: 'ZH' }, '8056': { ort: 'Zürich', kanton: 'ZH' }, '8057': { ort: 'Zürich', kanton: 'ZH' },
  '8058': { ort: 'Zürich', kanton: 'ZH' }, '8059': { ort: 'Zürich', kanton: 'ZH' }, '8060': { ort: 'Zürich', kanton: 'ZH' }, '8061': { ort: 'Zürich', kanton: 'ZH' },
  '8062': { ort: 'Zürich', kanton: 'ZH' }, '8063': { ort: 'Zürich', kanton: 'ZH' }, '8064': { ort: 'Zürich', kanton: 'ZH' }, '8065': { ort: 'Zürich', kanton: 'ZH' },
  '8066': { ort: 'Zürich', kanton: 'ZH' }, '8067': { ort: 'Zürich', kanton: 'ZH' }, '8068': { ort: 'Zürich', kanton: 'ZH' }, '8069': { ort: 'Zürich', kanton: 'ZH' },
  '8070': { ort: 'Zürich', kanton: 'ZH' }, '8071': { ort: 'Zürich', kanton: 'ZH' }, '8072': { ort: 'Zürich', kanton: 'ZH' }, '8073': { ort: 'Zürich', kanton: 'ZH' },
  '8074': { ort: 'Zürich', kanton: 'ZH' }, '8075': { ort: 'Zürich', kanton: 'ZH' }, '8076': { ort: 'Zürich', kanton: 'ZH' }, '8077': { ort: 'Zürich', kanton: 'ZH' },
  '8078': { ort: 'Zürich', kanton: 'ZH' }, '8079': { ort: 'Zürich', kanton: 'ZH' }, '8080': { ort: 'Zürich', kanton: 'ZH' }, '8081': { ort: 'Zürich', kanton: 'ZH' },
  '8082': { ort: 'Zürich', kanton: 'ZH' }, '8083': { ort: 'Zürich', kanton: 'ZH' }, '8084': { ort: 'Zürich', kanton: 'ZH' }, '8085': { ort: 'Zürich', kanton: 'ZH' },
  '8086': { ort: 'Zürich', kanton: 'ZH' }, '8087': { ort: 'Zürich', kanton: 'ZH' }, '8088': { ort: 'Zürich', kanton: 'ZH' }, '8089': { ort: 'Zürich', kanton: 'ZH' },
  '8090': { ort: 'Zürich', kanton: 'ZH' }, '8091': { ort: 'Zürich', kanton: 'ZH' }, '8092': { ort: 'Zürich', kanton: 'ZH' }, '8093': { ort: 'Zürich', kanton: 'ZH' },
  '8094': { ort: 'Zürich', kanton: 'ZH' }, '8095': { ort: 'Zürich', kanton: 'ZH' }, '8096': { ort: 'Zürich', kanton: 'ZH' }, '8097': { ort: 'Zürich', kanton: 'ZH' },
  '8098': { ort: 'Zürich', kanton: 'ZH' }, '8099': { ort: 'Zürich', kanton: 'ZH' },
  
  // Bern (BE) - Haupt-PLZs
  '3000': { ort: 'Bern', kanton: 'BE' }, '3001': { ort: 'Bern', kanton: 'BE' }, '3002': { ort: 'Bern', kanton: 'BE' }, '3003': { ort: 'Bern', kanton: 'BE' },
  '3004': { ort: 'Bern', kanton: 'BE' }, '3005': { ort: 'Bern', kanton: 'BE' }, '3006': { ort: 'Bern', kanton: 'BE' }, '3007': { ort: 'Bern', kanton: 'BE' },
  '3008': { ort: 'Bern', kanton: 'BE' }, '3009': { ort: 'Bern', kanton: 'BE' }, '3010': { ort: 'Bern', kanton: 'BE' }, '3011': { ort: 'Bern', kanton: 'BE' },
  '3012': { ort: 'Bern', kanton: 'BE' }, '3013': { ort: 'Bern', kanton: 'BE' }, '3014': { ort: 'Bern', kanton: 'BE' }, '3015': { ort: 'Bern', kanton: 'BE' },
  '3016': { ort: 'Bern', kanton: 'BE' }, '3017': { ort: 'Bern', kanton: 'BE' }, '3018': { ort: 'Bern', kanton: 'BE' }, '3019': { ort: 'Bern', kanton: 'BE' },
  '3020': { ort: 'Bern', kanton: 'BE' }, '3021': { ort: 'Bern', kanton: 'BE' }, '3022': { ort: 'Bern', kanton: 'BE' }, '3023': { ort: 'Bern', kanton: 'BE' },
  '3024': { ort: 'Bern', kanton: 'BE' }, '3025': { ort: 'Bern', kanton: 'BE' }, '3026': { ort: 'Bern', kanton: 'BE' }, '3027': { ort: 'Bern', kanton: 'BE' },
  '3028': { ort: 'Bern', kanton: 'BE' }, '3029': { ort: 'Bern', kanton: 'BE' }, '3030': { ort: 'Bern', kanton: 'BE' }, '3031': { ort: 'Bern', kanton: 'BE' },
  '3032': { ort: 'Bern', kanton: 'BE' }, '3033': { ort: 'Bern', kanton: 'BE' }, '3034': { ort: 'Bern', kanton: 'BE' }, '3035': { ort: 'Bern', kanton: 'BE' },
  '3036': { ort: 'Bern', kanton: 'BE' }, '3037': { ort: 'Bern', kanton: 'BE' }, '3038': { ort: 'Bern', kanton: 'BE' }, '3039': { ort: 'Bern', kanton: 'BE' },
  '3040': { ort: 'Bern', kanton: 'BE' }, '3041': { ort: 'Bern', kanton: 'BE' }, '3042': { ort: 'Bern', kanton: 'BE' }, '3043': { ort: 'Bern', kanton: 'BE' },
  '3044': { ort: 'Bern', kanton: 'BE' }, '3045': { ort: 'Bern', kanton: 'BE' }, '3046': { ort: 'Bern', kanton: 'BE' }, '3047': { ort: 'Bern', kanton: 'BE' },
  '3048': { ort: 'Bern', kanton: 'BE' }, '3049': { ort: 'Bern', kanton: 'BE' }, '3050': { ort: 'Bern', kanton: 'BE' }, '3051': { ort: 'Bern', kanton: 'BE' },
  '3052': { ort: 'Bern', kanton: 'BE' }, '3053': { ort: 'Bern', kanton: 'BE' }, '3054': { ort: 'Bern', kanton: 'BE' }, '3055': { ort: 'Bern', kanton: 'BE' },
  '3056': { ort: 'Bern', kanton: 'BE' }, '3057': { ort: 'Bern', kanton: 'BE' }, '3058': { ort: 'Bern', kanton: 'BE' }, '3059': { ort: 'Bern', kanton: 'BE' },
  '3060': { ort: 'Bern', kanton: 'BE' }, '3061': { ort: 'Bern', kanton: 'BE' }, '3062': { ort: 'Bern', kanton: 'BE' }, '3063': { ort: 'Bern', kanton: 'BE' },
  '3064': { ort: 'Bern', kanton: 'BE' }, '3065': { ort: 'Bern', kanton: 'BE' }, '3066': { ort: 'Bern', kanton: 'BE' }, '3067': { ort: 'Bern', kanton: 'BE' },
  '3068': { ort: 'Bern', kanton: 'BE' }, '3069': { ort: 'Bern', kanton: 'BE' }, '3070': { ort: 'Bern', kanton: 'BE' }, '3071': { ort: 'Bern', kanton: 'BE' },
  '3072': { ort: 'Bern', kanton: 'BE' }, '3073': { ort: 'Bern', kanton: 'BE' }, '3074': { ort: 'Bern', kanton: 'BE' }, '3075': { ort: 'Bern', kanton: 'BE' },
  '3076': { ort: 'Bern', kanton: 'BE' }, '3077': { ort: 'Bern', kanton: 'BE' }, '3078': { ort: 'Bern', kanton: 'BE' }, '3079': { ort: 'Bern', kanton: 'BE' },
  '3080': { ort: 'Bern', kanton: 'BE' }, '3081': { ort: 'Bern', kanton: 'BE' }, '3082': { ort: 'Bern', kanton: 'BE' }, '3083': { ort: 'Bern', kanton: 'BE' },
  '3084': { ort: 'Bern', kanton: 'BE' }, '3085': { ort: 'Bern', kanton: 'BE' }, '3086': { ort: 'Bern', kanton: 'BE' }, '3087': { ort: 'Bern', kanton: 'BE' },
  '3088': { ort: 'Bern', kanton: 'BE' }, '3089': { ort: 'Bern', kanton: 'BE' }, '3090': { ort: 'Bern', kanton: 'BE' }, '3091': { ort: 'Bern', kanton: 'BE' },
  '3092': { ort: 'Bern', kanton: 'BE' }, '3093': { ort: 'Bern', kanton: 'BE' }, '3094': { ort: 'Bern', kanton: 'BE' }, '3095': { ort: 'Bern', kanton: 'BE' },
  '3096': { ort: 'Bern', kanton: 'BE' }, '3097': { ort: 'Bern', kanton: 'BE' }, '3098': { ort: 'Bern', kanton: 'BE' }, '3099': { ort: 'Bern', kanton: 'BE' },
  
  // Basel-Stadt (BS)
  '4000': { ort: 'Basel', kanton: 'BS' }, '4001': { ort: 'Basel', kanton: 'BS' }, '4002': { ort: 'Basel', kanton: 'BS' }, '4003': { ort: 'Basel', kanton: 'BS' },
  '4004': { ort: 'Basel', kanton: 'BS' }, '4005': { ort: 'Basel', kanton: 'BS' }, '4006': { ort: 'Basel', kanton: 'BS' }, '4007': { ort: 'Basel', kanton: 'BS' },
  '4008': { ort: 'Basel', kanton: 'BS' }, '4009': { ort: 'Basel', kanton: 'BS' }, '4010': { ort: 'Basel', kanton: 'BS' }, '4011': { ort: 'Basel', kanton: 'BS' },
  '4012': { ort: 'Basel', kanton: 'BS' }, '4013': { ort: 'Basel', kanton: 'BS' }, '4014': { ort: 'Basel', kanton: 'BS' }, '4015': { ort: 'Basel', kanton: 'BS' },
  '4016': { ort: 'Basel', kanton: 'BS' }, '4017': { ort: 'Basel', kanton: 'BS' }, '4018': { ort: 'Basel', kanton: 'BS' }, '4019': { ort: 'Basel', kanton: 'BS' },
  '4020': { ort: 'Basel', kanton: 'BS' }, '4021': { ort: 'Basel', kanton: 'BS' }, '4022': { ort: 'Basel', kanton: 'BS' }, '4023': { ort: 'Basel', kanton: 'BS' },
  '4024': { ort: 'Basel', kanton: 'BS' }, '4025': { ort: 'Basel', kanton: 'BS' }, '4026': { ort: 'Basel', kanton: 'BS' }, '4027': { ort: 'Basel', kanton: 'BS' },
  '4028': { ort: 'Basel', kanton: 'BS' }, '4029': { ort: 'Basel', kanton: 'BS' }, '4030': { ort: 'Basel', kanton: 'BS' }, '4031': { ort: 'Basel', kanton: 'BS' },
  '4032': { ort: 'Basel', kanton: 'BS' }, '4033': { ort: 'Basel', kanton: 'BS' }, '4034': { ort: 'Basel', kanton: 'BS' }, '4035': { ort: 'Basel', kanton: 'BS' },
  '4036': { ort: 'Basel', kanton: 'BS' }, '4037': { ort: 'Basel', kanton: 'BS' }, '4038': { ort: 'Basel', kanton: 'BS' }, '4039': { ort: 'Basel', kanton: 'BS' },
  '4040': { ort: 'Basel', kanton: 'BS' }, '4041': { ort: 'Basel', kanton: 'BS' }, '4042': { ort: 'Basel', kanton: 'BS' }, '4043': { ort: 'Basel', kanton: 'BS' },
  '4044': { ort: 'Basel', kanton: 'BS' }, '4045': { ort: 'Basel', kanton: 'BS' }, '4046': { ort: 'Basel', kanton: 'BS' }, '4047': { ort: 'Basel', kanton: 'BS' },
  '4048': { ort: 'Basel', kanton: 'BS' }, '4049': { ort: 'Basel', kanton: 'BS' }, '4050': { ort: 'Basel', kanton: 'BS' }, '4051': { ort: 'Basel', kanton: 'BS' },
  '4052': { ort: 'Basel', kanton: 'BS' }, '4053': { ort: 'Basel', kanton: 'BS' }, '4054': { ort: 'Basel', kanton: 'BS' }, '4055': { ort: 'Basel', kanton: 'BS' },
  '4056': { ort: 'Basel', kanton: 'BS' }, '4057': { ort: 'Basel', kanton: 'BS' }, '4058': { ort: 'Basel', kanton: 'BS' }, '4059': { ort: 'Basel', kanton: 'BS' },
  '4060': { ort: 'Basel', kanton: 'BS' }, '4061': { ort: 'Basel', kanton: 'BS' }, '4062': { ort: 'Basel', kanton: 'BS' }, '4063': { ort: 'Basel', kanton: 'BS' },
  '4064': { ort: 'Basel', kanton: 'BS' }, '4065': { ort: 'Basel', kanton: 'BS' }, '4066': { ort: 'Basel', kanton: 'BS' }, '4067': { ort: 'Basel', kanton: 'BS' },
  '4068': { ort: 'Basel', kanton: 'BS' }, '4069': { ort: 'Basel', kanton: 'BS' }, '4070': { ort: 'Basel', kanton: 'BS' }, '4071': { ort: 'Basel', kanton: 'BS' },
  '4072': { ort: 'Basel', kanton: 'BS' }, '4073': { ort: 'Basel', kanton: 'BS' }, '4074': { ort: 'Basel', kanton: 'BS' }, '4075': { ort: 'Basel', kanton: 'BS' },
  '4076': { ort: 'Basel', kanton: 'BS' }, '4077': { ort: 'Basel', kanton: 'BS' }, '4078': { ort: 'Basel', kanton: 'BS' }, '4079': { ort: 'Basel', kanton: 'BS' },
  '4080': { ort: 'Basel', kanton: 'BS' }, '4081': { ort: 'Basel', kanton: 'BS' }, '4082': { ort: 'Basel', kanton: 'BS' }, '4083': { ort: 'Basel', kanton: 'BS' },
  '4084': { ort: 'Basel', kanton: 'BS' }, '4085': { ort: 'Basel', kanton: 'BS' }, '4086': { ort: 'Basel', kanton: 'BS' }, '4087': { ort: 'Basel', kanton: 'BS' },
  '4088': { ort: 'Basel', kanton: 'BS' }, '4089': { ort: 'Basel', kanton: 'BS' }, '4090': { ort: 'Basel', kanton: 'BS' }, '4091': { ort: 'Basel', kanton: 'BS' },
  '4092': { ort: 'Basel', kanton: 'BS' }, '4093': { ort: 'Basel', kanton: 'BS' }, '4094': { ort: 'Basel', kanton: 'BS' }, '4095': { ort: 'Basel', kanton: 'BS' },
  '4096': { ort: 'Basel', kanton: 'BS' }, '4097': { ort: 'Basel', kanton: 'BS' }, '4098': { ort: 'Basel', kanton: 'BS' }, '4099': { ort: 'Basel', kanton: 'BS' },
  
  // Luzern (LU) - Haupt-PLZs
  '6000': { ort: 'Luzern', kanton: 'LU' }, '6001': { ort: 'Luzern', kanton: 'LU' }, '6002': { ort: 'Luzern', kanton: 'LU' }, '6003': { ort: 'Luzern', kanton: 'LU' },
  '6004': { ort: 'Luzern', kanton: 'LU' }, '6005': { ort: 'Luzern', kanton: 'LU' }, '6006': { ort: 'Luzern', kanton: 'LU' }, '6007': { ort: 'Luzern', kanton: 'LU' },
  '6008': { ort: 'Luzern', kanton: 'LU' }, '6009': { ort: 'Luzern', kanton: 'LU' }, '6010': { ort: 'Luzern', kanton: 'LU' }, '6011': { ort: 'Luzern', kanton: 'LU' },
  '6012': { ort: 'Luzern', kanton: 'LU' }, '6013': { ort: 'Luzern', kanton: 'LU' }, '6014': { ort: 'Luzern', kanton: 'LU' }, '6015': { ort: 'Luzern', kanton: 'LU' },
  '6016': { ort: 'Luzern', kanton: 'LU' }, '6017': { ort: 'Luzern', kanton: 'LU' }, '6018': { ort: 'Luzern', kanton: 'LU' }, '6019': { ort: 'Luzern', kanton: 'LU' },
  '6020': { ort: 'Luzern', kanton: 'LU' }, '6021': { ort: 'Luzern', kanton: 'LU' }, '6022': { ort: 'Luzern', kanton: 'LU' }, '6023': { ort: 'Luzern', kanton: 'LU' },
  '6024': { ort: 'Luzern', kanton: 'LU' }, '6025': { ort: 'Luzern', kanton: 'LU' }, '6026': { ort: 'Luzern', kanton: 'LU' }, '6027': { ort: 'Luzern', kanton: 'LU' },
  '6028': { ort: 'Luzern', kanton: 'LU' }, '6029': { ort: 'Luzern', kanton: 'LU' }, '6030': { ort: 'Luzern', kanton: 'LU' }, '6031': { ort: 'Luzern', kanton: 'LU' },
  '6032': { ort: 'Luzern', kanton: 'LU' }, '6033': { ort: 'Luzern', kanton: 'LU' }, '6034': { ort: 'Luzern', kanton: 'LU' }, '6035': { ort: 'Luzern', kanton: 'LU' },
  '6036': { ort: 'Luzern', kanton: 'LU' }, '6037': { ort: 'Luzern', kanton: 'LU' }, '6038': { ort: 'Luzern', kanton: 'LU' }, '6039': { ort: 'Luzern', kanton: 'LU' },
  '6040': { ort: 'Luzern', kanton: 'LU' }, '6041': { ort: 'Luzern', kanton: 'LU' }, '6042': { ort: 'Luzern', kanton: 'LU' }, '6043': { ort: 'Luzern', kanton: 'LU' },
  '6044': { ort: 'Luzern', kanton: 'LU' }, '6045': { ort: 'Luzern', kanton: 'LU' }, '6046': { ort: 'Luzern', kanton: 'LU' }, '6047': { ort: 'Luzern', kanton: 'LU' },
  '6048': { ort: 'Luzern', kanton: 'LU' }, '6049': { ort: 'Luzern', kanton: 'LU' }, '6050': { ort: 'Luzern', kanton: 'LU' }, '6051': { ort: 'Luzern', kanton: 'LU' },
  '6052': { ort: 'Luzern', kanton: 'LU' }, '6053': { ort: 'Luzern', kanton: 'LU' }, '6054': { ort: 'Luzern', kanton: 'LU' }, '6055': { ort: 'Luzern', kanton: 'LU' },
  '6056': { ort: 'Luzern', kanton: 'LU' }, '6057': { ort: 'Luzern', kanton: 'LU' }, '6058': { ort: 'Luzern', kanton: 'LU' }, '6059': { ort: 'Luzern', kanton: 'LU' },
  '6060': { ort: 'Luzern', kanton: 'LU' }, '6061': { ort: 'Luzern', kanton: 'LU' }, '6062': { ort: 'Luzern', kanton: 'LU' }, '6063': { ort: 'Luzern', kanton: 'LU' },
  '6064': { ort: 'Luzern', kanton: 'LU' }, '6065': { ort: 'Luzern', kanton: 'LU' }, '6066': { ort: 'Luzern', kanton: 'LU' }, '6067': { ort: 'Luzern', kanton: 'LU' },
  '6068': { ort: 'Luzern', kanton: 'LU' }, '6069': { ort: 'Luzern', kanton: 'LU' }, '6070': { ort: 'Luzern', kanton: 'LU' }, '6071': { ort: 'Luzern', kanton: 'LU' },
  '6072': { ort: 'Luzern', kanton: 'LU' }, '6073': { ort: 'Luzern', kanton: 'LU' }, '6074': { ort: 'Luzern', kanton: 'LU' }, '6075': { ort: 'Luzern', kanton: 'LU' },
  '6076': { ort: 'Luzern', kanton: 'LU' }, '6077': { ort: 'Luzern', kanton: 'LU' }, '6078': { ort: 'Luzern', kanton: 'LU' }, '6079': { ort: 'Luzern', kanton: 'LU' },
  '6080': { ort: 'Luzern', kanton: 'LU' }, '6081': { ort: 'Luzern', kanton: 'LU' }, '6082': { ort: 'Luzern', kanton: 'LU' }, '6083': { ort: 'Luzern', kanton: 'LU' },
  '6084': { ort: 'Luzern', kanton: 'LU' }, '6085': { ort: 'Luzern', kanton: 'LU' }, '6086': { ort: 'Luzern', kanton: 'LU' }, '6087': { ort: 'Luzern', kanton: 'LU' },
  '6088': { ort: 'Luzern', kanton: 'LU' }, '6089': { ort: 'Luzern', kanton: 'LU' }, '6090': { ort: 'Luzern', kanton: 'LU' }, '6091': { ort: 'Luzern', kanton: 'LU' },
  '6092': { ort: 'Luzern', kanton: 'LU' }, '6093': { ort: 'Luzern', kanton: 'LU' }, '6094': { ort: 'Luzern', kanton: 'LU' }, '6095': { ort: 'Luzern', kanton: 'LU' },
  '6096': { ort: 'Luzern', kanton: 'LU' }, '6097': { ort: 'Luzern', kanton: 'LU' }, '6098': { ort: 'Luzern', kanton: 'LU' }, '6099': { ort: 'Luzern', kanton: 'LU' },
  
  // St. Gallen (SG) - Haupt-PLZs
  '9000': { ort: 'St. Gallen', kanton: 'SG' }, '9001': { ort: 'St. Gallen', kanton: 'SG' }, '9002': { ort: 'St. Gallen', kanton: 'SG' }, '9003': { ort: 'St. Gallen', kanton: 'SG' },
  '9004': { ort: 'St. Gallen', kanton: 'SG' }, '9005': { ort: 'St. Gallen', kanton: 'SG' }, '9006': { ort: 'St. Gallen', kanton: 'SG' }, '9007': { ort: 'St. Gallen', kanton: 'SG' },
  '9008': { ort: 'St. Gallen', kanton: 'SG' }, '9009': { ort: 'St. Gallen', kanton: 'SG' }, '9010': { ort: 'St. Gallen', kanton: 'SG' }, '9011': { ort: 'St. Gallen', kanton: 'SG' },
  '9012': { ort: 'St. Gallen', kanton: 'SG' }, '9013': { ort: 'St. Gallen', kanton: 'SG' }, '9014': { ort: 'St. Gallen', kanton: 'SG' }, '9015': { ort: 'St. Gallen', kanton: 'SG' },
  '9016': { ort: 'St. Gallen', kanton: 'SG' }, '9017': { ort: 'St. Gallen', kanton: 'SG' }, '9018': { ort: 'St. Gallen', kanton: 'SG' }, '9019': { ort: 'St. Gallen', kanton: 'SG' },
  '9020': { ort: 'St. Gallen', kanton: 'SG' }, '9021': { ort: 'St. Gallen', kanton: 'SG' }, '9022': { ort: 'St. Gallen', kanton: 'SG' }, '9023': { ort: 'St. Gallen', kanton: 'SG' },
  '9024': { ort: 'St. Gallen', kanton: 'SG' }, '9025': { ort: 'St. Gallen', kanton: 'SG' }, '9026': { ort: 'St. Gallen', kanton: 'SG' }, '9027': { ort: 'St. Gallen', kanton: 'SG' },
  '9028': { ort: 'St. Gallen', kanton: 'SG' }, '9029': { ort: 'St. Gallen', kanton: 'SG' }, '9030': { ort: 'St. Gallen', kanton: 'SG' }, '9031': { ort: 'St. Gallen', kanton: 'SG' },
  '9032': { ort: 'St. Gallen', kanton: 'SG' }, '9033': { ort: 'St. Gallen', kanton: 'SG' }, '9034': { ort: 'St. Gallen', kanton: 'SG' }, '9035': { ort: 'St. Gallen', kanton: 'SG' },
  '9036': { ort: 'St. Gallen', kanton: 'SG' }, '9037': { ort: 'St. Gallen', kanton: 'SG' }, '9038': { ort: 'St. Gallen', kanton: 'SG' }, '9039': { ort: 'St. Gallen', kanton: 'SG' },
  '9040': { ort: 'St. Gallen', kanton: 'SG' }, '9041': { ort: 'St. Gallen', kanton: 'SG' }, '9042': { ort: 'St. Gallen', kanton: 'SG' }, '9043': { ort: 'St. Gallen', kanton: 'SG' },
  '9044': { ort: 'St. Gallen', kanton: 'SG' }, '9045': { ort: 'St. Gallen', kanton: 'SG' }, '9046': { ort: 'St. Gallen', kanton: 'SG' }, '9047': { ort: 'St. Gallen', kanton: 'SG' },
  '9048': { ort: 'St. Gallen', kanton: 'SG' }, '9049': { ort: 'St. Gallen', kanton: 'SG' }, '9050': { ort: 'St. Gallen', kanton: 'SG' }, '9051': { ort: 'St. Gallen', kanton: 'SG' },
  '9052': { ort: 'St. Gallen', kanton: 'SG' }, '9053': { ort: 'St. Gallen', kanton: 'SG' }, '9054': { ort: 'St. Gallen', kanton: 'SG' }, '9055': { ort: 'St. Gallen', kanton: 'SG' },
  '9056': { ort: 'St. Gallen', kanton: 'SG' }, '9057': { ort: 'St. Gallen', kanton: 'SG' }, '9058': { ort: 'St. Gallen', kanton: 'SG' }, '9059': { ort: 'St. Gallen', kanton: 'SG' },
  '9060': { ort: 'St. Gallen', kanton: 'SG' }, '9061': { ort: 'St. Gallen', kanton: 'SG' }, '9062': { ort: 'St. Gallen', kanton: 'SG' }, '9063': { ort: 'St. Gallen', kanton: 'SG' },
  '9064': { ort: 'St. Gallen', kanton: 'SG' }, '9065': { ort: 'St. Gallen', kanton: 'SG' }, '9066': { ort: 'St. Gallen', kanton: 'SG' }, '9067': { ort: 'St. Gallen', kanton: 'SG' },
  '9068': { ort: 'St. Gallen', kanton: 'SG' }, '9069': { ort: 'St. Gallen', kanton: 'SG' }, '9070': { ort: 'St. Gallen', kanton: 'SG' }, '9071': { ort: 'St. Gallen', kanton: 'SG' },
  '9072': { ort: 'St. Gallen', kanton: 'SG' }, '9073': { ort: 'St. Gallen', kanton: 'SG' }, '9074': { ort: 'St. Gallen', kanton: 'SG' }, '9075': { ort: 'St. Gallen', kanton: 'SG' },
  '9076': { ort: 'St. Gallen', kanton: 'SG' }, '9077': { ort: 'St. Gallen', kanton: 'SG' }, '9078': { ort: 'St. Gallen', kanton: 'SG' }, '9079': { ort: 'St. Gallen', kanton: 'SG' },
  '9080': { ort: 'St. Gallen', kanton: 'SG' }, '9081': { ort: 'St. Gallen', kanton: 'SG' }, '9082': { ort: 'St. Gallen', kanton: 'SG' }, '9083': { ort: 'St. Gallen', kanton: 'SG' },
  '9084': { ort: 'St. Gallen', kanton: 'SG' }, '9085': { ort: 'St. Gallen', kanton: 'SG' }, '9086': { ort: 'St. Gallen', kanton: 'SG' }, '9087': { ort: 'St. Gallen', kanton: 'SG' },
  '9088': { ort: 'St. Gallen', kanton: 'SG' }, '9089': { ort: 'St. Gallen', kanton: 'SG' }, '9090': { ort: 'St. Gallen', kanton: 'SG' }, '9091': { ort: 'St. Gallen', kanton: 'SG' },
  '9092': { ort: 'St. Gallen', kanton: 'SG' }, '9093': { ort: 'St. Gallen', kanton: 'SG' }, '9094': { ort: 'St. Gallen', kanton: 'SG' }, '9095': { ort: 'St. Gallen', kanton: 'SG' },
  '9096': { ort: 'St. Gallen', kanton: 'SG' }, '9097': { ort: 'St. Gallen', kanton: 'SG' }, '9098': { ort: 'St. Gallen', kanton: 'SG' }, '9099': { ort: 'St. Gallen', kanton: 'SG' },
};